---
- hosts: KubCluster
  become: True
  tasks:
  - name: Install openscap
    apt:
      name: libopenscap8
      state: present
  - name: Transfer scap datastream
    copy: src=${XCCDF} dest=/tmp/${XCCDF} mode=0777
 
  - name: Execute static assessment
    command: oscap xccdf eval --profile ${XCCDF_PROFILE} --report /tmp/oscap_report.html /tmp/${XCCDF}
    register: result
    failed_when:
      - result.rc == 1
  
  - fetch:
      src: /tmp/oscap_report.html
      dest: ../Results/
